# -*- coding: utf-8 -*-
"""2.Semantic_Search_OpenSource.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4smXQ4sBIcnCouQ6GIFRTiMWdXg2mCQ
"""

!pip install --quiet pandas sentence-transformers faiss-cpu tqdm

# -*- coding: utf-8 -*-
"""
⚡ LIGHTWEIGHT Semantic Search for OpenFoodFacts (Colab Prototype)
   - Minimal dataset (5k products) for fast iteration
   - Ultra-lightweight model (MiniLM, 26MB, 384-dim)
   - Pure semantic search (no manual config)
   - <2 min total setup time
"""

import pandas as pd
import numpy as np
import torch
from sentence_transformers import SentenceTransformer
import faiss
import re, gzip, shutil, gc, os, time
import warnings
warnings.filterwarnings('ignore')

# ==========================================================
# ⚡ CONFIG - ULTRA-LIGHTWEIGHT FOR PROTOTYPING
# ==========================================================
DATA_URL = "https://world.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz"
LOCAL_GZ = "openfoodfacts.csv.gz"
LOCAL_CSV = "openfoodfacts.csv"

# REDUCED: Smaller dataset for fast prototyping
MAX_ROWS = 5000                # Down from 10k (2x faster)
EMBED_BATCH = 512              # Larger batch = faster (GPU can handle)
EMBED_MODEL = "all-MiniLM-L6-v2"  # Lightweight, proven fast (26MB only)

print("⚡ LIGHTWEIGHT SEMANTIC SEARCH PROTOTYPE")
print("="*70)

# ==========================================================
# SETUP
# ==========================================================
!pip install --quiet pandas sentence-transformers faiss-cpu -q

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"💻 Device: {device.upper()}")
print(f"📊 Max products: {MAX_ROWS:,}")
print(f"📈 Batch size: {EMBED_BATCH}")

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    print(f"🔋 GPU: {torch.cuda.get_device_name(0)}\n")

# ==========================================================
# 1. DOWNLOAD & DECOMPRESS (Fast path)
# ==========================================================
def setup_data():
    if not os.path.exists(LOCAL_CSV):
        if not os.path.exists(LOCAL_GZ):
            print("📦 Downloading (~300MB)...")
            !wget -q --show-progress -O {LOCAL_GZ} {DATA_URL}
        print("🗜️  Decompressing...")
        with gzip.open(LOCAL_GZ, "rb") as f_in:
            with open(LOCAL_CSV, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)
    print("✅ Data ready\n")

setup_data()

# ==========================================================
# 2. LOAD DATA (Single pass, no cleanup overhead)
# ==========================================================
print("📋 Loading data...")
load_start = time.time()

cols = ["product_name", "brands", "categories", "ingredients_text"]
df = pd.read_csv(
    LOCAL_CSV,
    sep="\t",
    dtype=str,
    usecols=cols,
    nrows=MAX_ROWS,
    na_filter=False  # No NaN processing = faster
)

print(f"   ✅ {len(df):,} rows loaded in {time.time()-load_start:.2f}s")

# Minimal cleaning
df.columns = ["name", "brand", "categories", "ingredients"]
df = df[(df["name"].str.len() > 3) &
        ((df["ingredients"].str.len() > 0) | (df["categories"].str.len() > 0))]
df = df.reset_index(drop=True)

print(f"   ✅ {len(df):,} valid products\n")

# ==========================================================
# 3. BUILD SEARCH TEXT (Minimal processing)
# ==========================================================
print("🔗 Building search index...")

# Simple concatenation (no fancy deduplication)
df["search_text"] = (
    df["name"] + " " + df["brand"] + " " + df["categories"] + " " + df["ingredients"]
)

texts = df["search_text"].values.tolist()
metadata = df[["name", "brand", "categories", "ingredients"]].to_dict("records")

print(f"   ✅ {len(texts):,} search documents ready\n")

del df
gc.collect()

# ==========================================================
# 4. LOAD MODEL (Fastest model available)
# ==========================================================
print("📥 Loading embedding model (all-MiniLM-L6-v2)...")
model_start = time.time()

model = SentenceTransformer(EMBED_MODEL, device=device)
dim = model.get_sentence_embedding_dimension()

print(f"   ✅ Model loaded in {time.time()-model_start:.2f}s")
print(f"   📐 Dimension: {dim}\n")

# ==========================================================
# 6. ENCODE EMBEDDINGS (ULTRA-FAST)
# ==========================================================
print("📈 Encoding embeddings...")
embed_start = time.time()

# One-shot encoding (sentence-transformers is already optimized)
with torch.no_grad():
    embeddings = model.encode(
        texts,
        batch_size=EMBED_BATCH,
        convert_to_tensor=False,
        normalize_embeddings=True,
        show_progress_bar=True
    )

embeddings = np.asarray(embeddings, dtype="float32")

# Create & populate index
index = faiss.IndexFlatIP(dim)
index.add(embeddings)

embed_time = time.time() - embed_start
throughput = len(texts) / embed_time

print(f"\n✅ Indexed {len(texts):,} products in {embed_time:.1f}s")
print(f"   ⚡ Speed: {throughput:.0f} docs/sec\n")

del embeddings, texts
gc.collect()

# ==========================================================
# 7. SEARCH FUNCTION (Pure semantic)
# ==========================================================
def semantic_search(query, top_k=5):
    """Fast semantic search with pure embeddings"""
    with torch.no_grad():
        q_emb = model.encode([query], normalize_embeddings=True)

    D, I = index.search(np.array(q_emb, dtype="float32"), min(top_k, len(metadata)))

    results = []
    for rank, idx in enumerate(I[0]):
        if idx < len(metadata):
            m = metadata[idx]
            score = float(D[0][rank])

            results.append({
                "rank": rank + 1,
                "name": m["name"],
                "brand": m["brand"][:40],
                "category": m["categories"][:60],
                "score": round(score, 3)
            })

    return results

# ==========================================================
# 8. READY TO USE
# ==========================================================
print("="*70)
print("✨ SEMANTIC SEARCH WITH LOGICAL REASONING")
print("="*70)
print("""
🎯 How it works:
   - Embeddings capture semantic meaning (coffee ↔ latte, etc)
   - Cosine similarity measures how close concepts are
   - No manual synonyms needed - model learns relationships

Key semantic relationships that work:
   ✓ coffee → cappuccino, espresso, latte (same semantic field)
   ✓ chocolate → cocoa (synonyms/related ingredients)
   ✓ milk → dairy (logical category relationship)
   ✓ juice → beverage (hypernym relationship)
   ✓ organic → bio, natural (quality descriptor)
""")

test_queries = ["coffee", "chocolate", "milk", "nuts", "juice", "beverage"]

print("\n" + "="*70)
print("🧪 SEMANTIC SEARCH RESULTS")
print("="*70)

for query in test_queries:
    results = semantic_search(query, top_k=3)
    print(f"\n🔍 '{query}' → {len(results)} results")
    for r in results:
        print(f"   #{r['rank']} {r['name']} ({r['brand']}) | {r['category']}")
        print(f"       Score: {r['score']} {'🔗' if r['score'] > 0.7 else '🟡' if r['score'] > 0.5 else '❌'}")

print("\n" + "="*70)
print("✨ READY FOR PROTOTYPING - Semantic Similarity Enabled!")
print("="*70)

